-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 19:34:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`doctor_kkr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doctor_kkr` (
  `id_doc` INT NOT NULL AUTO_INCREMENT,
  `doc_firstname` VARCHAR(55) NOT NULL,
  `doc_lastname` VARCHAR(55) NOT NULL,
  `doc_specialty` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_doc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`insurance_company_kkr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`insurance_company_kkr` (
  `id_ins` INT NOT NULL AUTO_INCREMENT,
  `ins_name` VARCHAR(100) NOT NULL,
  `ins_phone_number` VARCHAR(45) NOT NULL,
  `ins_address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_ins`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`patient_kkr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`patient_kkr` (
  `id_pat` INT NULL AUTO_INCREMENT,
  `pat_firstname` VARCHAR(55) NOT NULL,
  `pat_lastname` VARCHAR(55) NOT NULL,
  `pat_address` VARCHAR(255) NOT NULL,
  `pat_city` VARCHAR(100) NOT NULL,
  `insurance_company_kkr_id_ins` INT NULL,
  PRIMARY KEY (`id_pat`, `insurance_company_kkr_id_ins`),
  INDEX `fk_patient_kkr_insurance_company_kkr1_idx` (`insurance_company_kkr_id_ins` ASC) VISIBLE,
  CONSTRAINT `fk_patient_kkr_insurance_company_kkr1`
    FOREIGN KEY (`insurance_company_kkr_id_ins`)
    REFERENCES `mydb`.`insurance_company_kkr` (`id_ins`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apponiment_kkr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apponiment_kkr` (
  `id_app` INT NOT NULL AUTO_INCREMENT,
  `app_date` DATE NOT NULL,
  `app_time` TIME NOT NULL,
  `doctor_kkr_id_doc` INT NOT NULL,
  `patient_kkr_id_pat` INT NOT NULL,
  `doctor_kkr_id_doc1` INT NOT NULL,
  `patient_kkr_id_pat1` INT NOT NULL,
  `patient_kkr_insurance_company_kkr_id_ins` INT NOT NULL,
  PRIMARY KEY (`id_app`, `doctor_kkr_id_doc`, `patient_kkr_id_pat`),
  INDEX `fk_apponiment_kkr_doctor_kkr1_idx` (`doctor_kkr_id_doc1` ASC) VISIBLE,
  INDEX `fk_apponiment_kkr_patient_kkr1_idx` (`patient_kkr_id_pat1` ASC, `patient_kkr_insurance_company_kkr_id_ins` ASC) VISIBLE,
  CONSTRAINT `fk_apponiment_kkr_doctor_kkr1`
    FOREIGN KEY (`doctor_kkr_id_doc1`)
    REFERENCES `mydb`.`doctor_kkr` (`id_doc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apponiment_kkr_patient_kkr1`
    FOREIGN KEY (`patient_kkr_id_pat1` , `patient_kkr_insurance_company_kkr_id_ins`)
    REFERENCES `mydb`.`patient_kkr` (`id_pat` , `insurance_company_kkr_id_ins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bill_kkr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bill_kkr` (
  `id_bill` INT NOT NULL AUTO_INCREMENT,
  `bill_is_amount_insured` TINYINT(1) NOT NULL,
  `bill_datesent` DATE NOT NULL,
  `bill_status` TINYINT(1) NOT NULL DEFAULT 0,
  `apponiment_kkr_id_app` INT NOT NULL,
  `apponiment_kkr_doctor_kkr_id_doc` INT NOT NULL,
  `apponiment_kkr_patient_kkr_id_pat` INT NOT NULL,
  PRIMARY KEY (`id_bill`, `apponiment_kkr_id_app`, `apponiment_kkr_doctor_kkr_id_doc`, `apponiment_kkr_patient_kkr_id_pat`),
  INDEX `fk_bill_kkr_apponiment_kkr1_idx` (`apponiment_kkr_id_app` ASC, `apponiment_kkr_doctor_kkr_id_doc` ASC, `apponiment_kkr_patient_kkr_id_pat` ASC) VISIBLE,
  CONSTRAINT `fk_bill_kkr_apponiment_kkr1`
    FOREIGN KEY (`apponiment_kkr_id_app` , `apponiment_kkr_doctor_kkr_id_doc` , `apponiment_kkr_patient_kkr_id_pat`)
    REFERENCES `mydb`.`apponiment_kkr` (`id_app` , `doctor_kkr_id_doc` , `patient_kkr_id_pat`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`payment_kkr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`payment_kkr` (
  `id_pay` INT NOT NULL,
  `pay_amount` DECIMAL(10,2) NOT NULL,
  `pay_date` DATE NOT NULL,
  `pay_method` VARCHAR(45) NOT NULL,
  `insurance_company_kkr_id_ins` INT NOT NULL,
  `bill_kkr_id_bill` INT NOT NULL,
  PRIMARY KEY (`id_pay`, `insurance_company_kkr_id_ins`, `bill_kkr_id_bill`),
  INDEX `fk_payment_kkr_insurance_company_kkr1_idx` (`insurance_company_kkr_id_ins` ASC) VISIBLE,
  INDEX `fk_payment_kkr_bill_kkr1_idx` (`bill_kkr_id_bill` ASC) VISIBLE,
  CONSTRAINT `pay_pat`
    FOREIGN KEY ()
    REFERENCES `mydb`.`patient_kkr` ()
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_kkr_insurance_company_kkr1`
    FOREIGN KEY (`insurance_company_kkr_id_ins`)
    REFERENCES `mydb`.`insurance_company_kkr` (`id_ins`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_kkr_bill_kkr1`
    FOREIGN KEY (`bill_kkr_id_bill`)
    REFERENCES `mydb`.`bill_kkr` (`id_bill`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
